### PR TITLE
ad57xx: add testbench

### PR DESCRIPTION
**Pull request by LBFFilho**
Add testbench for the ad57xx project. This testbench is accompanied by the corresponding hdl code at https://github.com/analogdevicesinc/hdl/pull/1467.

This also depends on https://github.com/analogdevicesinc/hdl/pull/1475 for connecting SPI VIP to the SPI interface on the block diagram.

### CODE REVIEW

**Review by gastmaier — CHANGES_REQUESTED** [review]
Brother patch for HDL review
I did not review this PR yet, the sim seems ok
[0001-REVIEW-V0-Reorder-SDO_STREAMING.patch](https://github.com/user-attachments/files/17168809/0001-REVIEW-V0-Reorder-SDO_STREAMING.patch)

**Review by gastmaier — CHANGES_REQUESTED** [review]
[0001-REVIEW-V1-Whitespace-minor-fixes-license.patch](https://github.com/user-attachments/files/17169163/0001-REVIEW-V1-Whitespace-minor-fixes-license.patch)

**Review by gastmaier — COMMENTED** [review]
Ok

**Review by gastmaier — APPROVED** [review]

**Comment by LBFFilho** [comment]
waiting for https://github.com/analogdevicesinc/hdl/pull/1475 before merging this

**Pull request merged**
